/**
 * Languages supported by OpenWeatherMap for translating the weather descriptions.
 *
 * Used in the `lang=` parameter.
 *
 * See {@link https://openweathermap.org/api/one-call-api#multi Translating summaries} for more information.
 */
export enum Language {
  Afrikaans = "af",
  Albanian = "al",
  Arabic = "ar",
  Azerbaijani = "az",
  Bulgarian = "bg",
  Catalan = "ca",
  Czech = "cz",
  Danish = "da",
  German = "de",
  Greek = "el",
  English = "en",
  Basque = "eu",
  Persian = "fa",
  Finnish = "fi",
  French = "fr",
  Galician = "gl",
  Hebrew = "he",
  Hindi = "hi",
  Croatian = "hr",
  Hungarian = "hu",
  Indonesian = "id",
  Italian = "it",
  Japanese = "ja",
  Korean = "kr",
  Latvian = "la",
  Lithuanian = "lt",
  Macedonian = "mk",
  Norwegian = "no",
  Dutch = "nl",
  Polish = "pl",
  Portuguese = "pt",
  Portuguese_Brazil = "pt_br",
  Romanian = "ro",
  Russian = "ru",
  Swedish = "sv",
  Slovak = "sk",
  Slovenian = "sl",
  Spanish = "sp",
  Serbian = "sr",
  Thai = "th",
  Turkish = "tr",
  Ukrainian = "ua",
  Vietnamese = "vi",
  Chinese_Simplified = "zh_cn",
  Chinese_Traditional = "zh_tw",
  Zulu = "zu",
}
